/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package 조성환;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        HelloToYou classUnderTest = new HelloToYou();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
